### ISSUE TITLE
Would you release your training code? The part of Synthetic ordering strokes data generation is really helpful to support my work.

### ISSUE THREAD

**Issue by yonglezhang95** [BlockDetail/Block-and-Detail#1]
Hello, 

The part about synthetic data generation of ordering strokes is really helpful in supporting my work. Would you release your code or email me at zhangyongle@stu.ouc.edu.cn?

Thanks

**Comment by kangyeolk** [comment]
Same here 👀

**Comment by sylviayuan-sy** [comment]
We have pushed our sketch generation code and related instructions.
